[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test-foundry"
solc = "0.8.28"
viaIR = true
optimizer = true
optimizerRuns = 200


[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${process.env.SEPOLIA_API_KEY}"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
op_sepolia = "https://sepolia.optimism.io"
amoy = "https://rpc-amoy.polygon.technology"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
